version: '3.1'
services:
  web:
    image: odoo:15
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./data/libodoo:/var/lib/odoo
      - ./data/config:/etc/odoo
      - ./data/addons:/mnt/extra-addons
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/bdd:/var/lib/postgresql/data/